### ISSUE TITLE
PlayerLoginEvent Error

### ISSUE THREAD

**Issue by anyecraft** [u2g/MoonLake#53]
```
[13:25:14] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to MoonLake v2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot.jar:git-Paper-1298]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-Paper-1298]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-Paper-1298]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [PaperSpigot.jar:git-Paper-1298]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:559) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:149) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:65) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot.jar:git-Paper-1298]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: com.mcmoonlake.api.exception.MoonLakeException: java.lang.NullPointerException
	at com.mcmoonlake.api.MoonLakeAPI.throwMoonLake(MoonLakeAPI.kt:227) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.api.reflect.accessor.Accessors$AccessorFieldSimple.get(Accessors.kt:221) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.api.utility.MinecraftPlayerMembers$NETWORK_MANAGER.get(MinecraftPlayerMembers.kt:72) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.api.utility.MinecraftPlayerMembers$CHANNEL.get(MinecraftPlayerMembers.kt:86) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl.getChannelPlayer(ServicePacketListenerImpl.kt:168) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl.injectChannelPlayer(ServicePacketListenerImpl.kt:171) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl.access$injectChannelPlayer(ServicePacketListenerImpl.kt:44) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl$onInitialized$listener$1.onLogin(ServicePacketListenerImpl.kt:52) ~[MoonLakePlugin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor138.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot.jar:git-Paper-1298]
	... 14 more
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Field.get(Unknown Source) ~[?:1.8.0_161]
	at com.mcmoonlake.api.reflect.accessor.Accessors$AccessorFieldSimple.get(Accessors.kt:216) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.api.utility.MinecraftPlayerMembers$NETWORK_MANAGER.get(MinecraftPlayerMembers.kt:72) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.api.utility.MinecraftPlayerMembers$CHANNEL.get(MinecraftPlayerMembers.kt:86) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl.getChannelPlayer(ServicePacketListenerImpl.kt:168) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl.injectChannelPlayer(ServicePacketListenerImpl.kt:171) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl.access$injectChannelPlayer(ServicePacketListenerImpl.kt:44) ~[MoonLakePlugin.jar:?]
	at com.mcmoonlake.impl.service.ServicePacketListenerImpl$onInitialized$listener$1.onLogin(ServicePacketListenerImpl.kt:52) ~[MoonLakePlugin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor138.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot.jar:git-Paper-1298]
	... 14 more
```

**Comment by lgou2w** [comment]
Try using the latest version of build. [Destroystokyo Paper](https://ci.destroystokyo.com/job/Paper/).

**Comment by lgou2w** [comment]
The problem should be `late-bind: true` in `spigot.yml`.

**Comment by lgou2w** [comment]
fixed. Thanks for the feedback.
